@startuml вшфп

skinparam packageStyle rectangle
skinparam defaultTextAlignment center

package "public/" {
  [index.html]
  [login.html]
  [register.html]
  [progress.html]
  [levels.html]
  [panorama.html]
  [how-it-works.html]
  [style.css]

  [auth.js]
  [levels.js]
  [main.js]
  [panorama.js]
  [progress.js]
}

package "server/" {
  [app.js]
  [auth.route.js]
  [progress.route.js]
  [knex.js]
}

database "MySQL" as DB

' HTML to CSS
[index.html] --> [style.css]
[login.html] --> [style.css]
[register.html] --> [style.css]
[progress.html] --> [style.css]
[levels.html] --> [style.css]
[panorama.html] --> [style.css]
[how-it-works.html] --> [style.css]

' HTML to JS
[index.html] --> [main.js]
[login.html] --> [auth.js]
[register.html] --> [auth.js]
[progress.html] --> [progress.js]
[levels.html] --> [levels.js]
[panorama.html] --> [panorama.js]
[register.html] --> [main.js]
[progress.html] --> [main.js]
[levels.html] --> [main.js]
[panorama.html] --> [main.js]

' Frontend JS interdependencies
[main.js] --> [auth.js]
[main.js] --> [levels.js]
[main.js] --> [progress.js]

' JS to backend
[auth.js] --> [auth.route.js]
[panorama.js] --> [progress.route.js]
[progress.js] --> [progress.route.js]

' Server setup
[app.js] --> [auth.route.js]
[app.js] --> [progress.route.js]
[auth.route.js] --> [knex.js]
[progress.route.js] --> [knex.js]
[knex.js] --> DB

@enduml
